# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  #PRODUCT SERVICES
  #ToDo 11: Define get_product service
  #Tip: The service is already created inside the Service folder, you just have to declare it!
  get_product:
    class: AppBundle\Service\GetProducts
    arguments: ["@product_repository"]

  import_products:
    class: AppBundle\Service\ImportProducts
    arguments: ["@product_repository"]

  string_format:
    class: AppBundle\Service\StringFormat

  #REPOSITORY SERVICES
  product_repository:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.default_entity_manager', 'getRepository']
    arguments: ['AppBundle\Entity\Product']
